### ISSUE TITLE
Improve star-randsrv's performance

### ISSUE THREAD

**Issue by NullHypothesis** [brave/star-randsrv#58]
Ideally, star-randsrv would be fast enough for us to not rely on horizontal scaling — at least for a while. Let's use this issue to explore optimizations. Here's what we have thought of so far:

- [x] Use a beefier EC2 instance type. We're currently using ~m5.xlarge~ m6i.4xlarge.
- [ ] Maximize the MTU between gvproxy and nitriding.
- [ ] Nitriding's reverse proxy is slow. We could teach star-randsrv to expose its own HTTPS server. This requires some work though.
- [ ] Test if gvproxy is a bottleneck here. If so, see how we could improve it.

**Comment by rillian** [comment]
gvproxy definitely seems to be a bottleneck in our early tests with production flows.

**Comment by rillian** [comment]
@DJAndries also reports the app running much slower inside an AWS Nitro enclave than outside, with the same cpu allocation. Something with the enclave-specific kernel maybe?

In this vein, I wondered if `OsRng` might be a source of syscall overhead, since we could replace that with the much faster `ThreadRng` but it doesn't look like it. We call it to generate a new OPRF key (so very infrequently) and to generate an ZK proof, but star-randsrv doesn't currently enable that.

**Comment by NullHypothesis** [comment]
> Something with the enclave-specific kernel maybe?

I remember being told by someone from AWS that they are using a custom (?) runtime engine for the enclave image. That's the reason why everything is running under UID 0. This runtime may also contribute to the performance issues we're seeing.

**Comment by DJAndries** [comment]
It's worth noting that removing usages of `Arc` doubled the throughput. It resulted in less futex syscall calls being made.
